DROP TABLE IF EXISTS Kayttaja CASCADE;

DROP TABLE IF EXISTS Tapahtuma CASCADE;

DROP TABLE IF EXISTS Osallistuminen CASCADE;

DROP TABLE IF EXISTS Extrapisteet CASCADE;

DROP TABLE IF EXISTS Fuksiryhma CASCADE;